### PR TITLE
Documentation fix (2nd time)

### PR DESCRIPTION
**Pull request by importhuman**

### CODE REVIEW

**Comment by DiptoChakrabarty** [comment]
hey @importhuman  this looks correct , could you please send the PR to the development branch and I will merge it to the master branch after it is merged as per the flow.

**Comment by importhuman** [comment]
Sure, do I have to make a new PR or can it be done from here?

**Comment by DiptoChakrabarty** [comment]
> Sure, do I have to make a new PR or can it be done from here?

Just change branch from master to development in the PR

**Comment by importhuman** [comment]
Done.

**Review by DiptoChakrabarty — APPROVED** [review]

**Pull request merged**
