### PR TITLE
Fixed date validation, removed whitespace in README.md

### PR DESCRIPTION
**Pull request by importhuman**
I had removed some whitespace from the coding blocks in installation process in README file, but it has since been changed in the master branch. Can it still be merged?

### CODE REVIEW

**Comment by DiptoChakrabarty** [comment]
There seem to be some  conflicts in the test.py file if you fix that I can review and merge

**Comment by importhuman** [comment]
Done.

**Review by DiptoChakrabarty — APPROVED** [review]

**Comment by DiptoChakrabarty** [comment]
Thanks its working fine

**Comment by importhuman** [comment]
My pleasure :)

**Pull request merged**
